### ISSUE TITLE
Apple Data refreshing up to 2020-12-31

### ISSUE THREAD

**Issue by sergiopapp** [Covid19R/covid19mobility#7]
Dear Jarrett and Amanda,

I have been using the covid19mobility R package to monitor Apple mobility Data. However, over the last two weeks I have not been able to refresh Apple City Data beyond 2020-12-31. Is there any problem with 2021 data?
```r
# library(covid19mobility)
data <- refresh_covid19mobility_apple_city() 
```

**Comment by jebyrnes** [comment]
Huh. It's possible the data source has changed. What message do you get if you try and refresh the data?

**Comment by sergiopapp** [comment]
No message at all. I can view the data in R after running the refresh function, but dates go up to 2020-12-31. Initially I thought Apple stopped producing it, but then I checked on their website and the latest data is 2021-01-25

**Comment by alanponce** [comment]
Same issue, any clue?

**Comment by jebyrnes** [comment]
This is really sad, you all. I wrote this package - and parsed some things out using the year - 2020 - to pivot the data. Because I assumed the pandemic would be over by 2021.

*sad trombone*

I will fix this and push it once testing is complete.

**Comment by jebyrnes** [comment]
Fixed in the github repo. Found one other bug. Will fix and resubmit to CRAN. But for now, you can use this version.

**Comment by sergiopapp** [comment]
Thank you very much, the fix worked!
